//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChucVuNhanVien
    {
        public ChucVuNhanVien()
        {
            this.NhanViens = new HashSet<NhanVien>();
        }
    
        public string MaChucVuNV { get; set; }
        public string TenChucVu { get; set; }
        public Nullable<double> HSPC { get; set; }
    
        public virtual ICollection<NhanVien> NhanViens { get; set; }
    }
}
