//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LuanChuyenNhanVien
    {
        public string MaNhanVien { get; set; }
        public int id { get; set; }
        public System.DateTime NgayChuyen { get; set; }
        public string LyDoChuyen { get; set; }
        public string PhongBanChuyen { get; set; }
        public string PhongBanDen { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
