//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyNhanSuEntities : DbContext
    {
        public QuanLyNhanSuEntities()
            : base("name=QuanLyNhanSuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CapNhatLuongs> CapNhatLuongs { get; set; }
        public virtual DbSet<CapNhatTrinhDoHocVans> CapNhatTrinhDoHocVans { get; set; }
        public virtual DbSet<ChiTietLuongs> ChiTietLuongs { get; set; }
        public virtual DbSet<ChucVuNhanViens> ChucVuNhanViens { get; set; }
        public virtual DbSet<ChuyenNganhs> ChuyenNganhs { get; set; }
        public virtual DbSet<HopDongs> HopDongs { get; set; }
        public virtual DbSet<KyLuats> KyLuats { get; set; }
        public virtual DbSet<KhenThuongs> KhenThuongs { get; set; }
        public virtual DbSet<LuanChuyenNhanViens> LuanChuyenNhanViens { get; set; }
        public virtual DbSet<LuongA1GV> LuongA1GV { get; set; }
        public virtual DbSet<LuongA21PGS> LuongA21PGS { get; set; }
        public virtual DbSet<LuongA31GS> LuongA31GS { get; set; }
        public virtual DbSet<Luongs> Luongs { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<NhanViens> NhanViens { get; set; }
        public virtual DbSet<PhongBans> PhongBans { get; set; }
        public virtual DbSet<SlideImages> SlideImages { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ThoiViecs> ThoiViecs { get; set; }
        public virtual DbSet<TrinhDoHocVans> TrinhDoHocVans { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
    }
}
