//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanViens
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanViens()
        {
            this.CapNhatTrinhDoHocVans = new HashSet<CapNhatTrinhDoHocVans>();
            this.LuanChuyenNhanViens = new HashSet<LuanChuyenNhanViens>();
        }
    
        public string MaNhanVien { get; set; }
        public string MatKhau { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string QueQuan { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<int> GioiTinh { get; set; }
        public string DanToc { get; set; }
        public string sdt_NhanVien { get; set; }
        public string MaChucVuNV { get; set; }
        public bool TrangThai { get; set; }
        public string MaPhongBan { get; set; }
        public string MaHopDong { get; set; }
        public string MaChuyenNganh { get; set; }
        public string MaTrinhDoHocVan { get; set; }
        public string CMND { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string delete_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CapNhatTrinhDoHocVans> CapNhatTrinhDoHocVans { get; set; }
        public virtual ChucVuNhanViens ChucVuNhanViens { get; set; }
        public virtual ChuyenNganhs ChuyenNganhs { get; set; }
        public virtual HopDongs HopDongs { get; set; }
        public virtual KyLuats KyLuats { get; set; }
        public virtual KhenThuongs KhenThuongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LuanChuyenNhanViens> LuanChuyenNhanViens { get; set; }
        public virtual Luongs Luongs { get; set; }
        public virtual PhongBans PhongBans { get; set; }
        public virtual ThoiViecs ThoiViecs { get; set; }
        public virtual TrinhDoHocVans TrinhDoHocVans { get; set; }
    }
}
